### ISSUE TITLE
Use of C++11

### ISSUE THREAD

**Issue by kunaltyagi** [ros/class_loader#100]
## Background Information
The packages `rosbag` and  `rosbag_store` includes headers from this package when the minimal installation from source is attempted. ROS assumes C++98, not C++11 and so the CMakeLists.txt don't have
```cmake
set(CMAKE_CXX_STANDARD 11) # or 14 or 17, but 11 suffices for compilation
```

## Issue
This package uses several new features of C++11 (and newer) including `std::shared_ptr<T>`, `std::unique_ptr<T>`, `nullptr` despite boost being the default standard in ROS.

This causes compilation error (which is easily fixed).

## Solution
Either 
* The CMakeLists.txt file of dependencies need to be changes and sacrifice portability for compilers not supporting C++11 or later

OR
* Changes need to be made in this repository to accommodate the compatibility issue.

After the discussion, I'd be happy to send PR to whatever solution is deemed as the correct one.

**Comment by mikaelarguedas** [comment]
Can you please clarify what version (or branch) of class_loader you are compiling as well as what version of ROS you are using ? Thanks

**Comment by kunaltyagi** [comment]
Oops, sorry for forgetting that. Melodic from `rosinstall_generator ros_comm --rosdistro melodic --deps --tar > melodic-ros_comm.rosinstall`

**Comment by mikaelarguedas** [comment]
Melodic targets only platforms that have c++14 as their default compiler option:
https://github.com/ros-infrastructure/rep/blob/master/rep-0003.rst#melodic-morenia-may-2018---may-2023
And assumes C++14 not C++98: https://github.com/ros-infrastructure/rep/blob/master/rep-0003.rst#melodic

Could you clarify your use case / setup?

**Comment by kunaltyagi** [comment]
I understand the fact that c++14 is the default compiler option on the target platforms.

In that case, should I go ahead with a PR on the rosbag repository for adding the definition explicitly? There's no harm in adding the c++ standard required. Our default compiler has c++14 support but not by default...

Thanks for the links. It seems I was stuck in the past

**Comment by mikaelarguedas** [comment]
> There's no harm in adding the c++ standard required.

This will force users to compile the code with the standard hard-coded in the package. If users have compiler defaulting to a higher standard I don't think we should force a downgrade on them

> In that case, should I go ahead with a PR on the rosbag repository for adding the definition explicitly? 

The policy applies to the entire distribution, I don't think submitting patches to specific packages is a desired approach as this will introduce inconsistencies between packages of the same distribution.

> Our default compiler has c++14 support but not by default...

Then I recommend you to pass the c++ standard explicitely to your build tool (or in its configuration if it supports it). e.g. MacOS users currently build by passing `-DCMAKE_CXX_STANDARD=14` to their build tools

You can find a similar discussion at https://github.com/ros/catkin/issues/936
