### ISSUE TITLE
Method createSharedInstance missing in ROS2 branches

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros/class_loader#165]
When porting to ROS2 we noticed that [createSharedInstance](https://github.com/ros/class_loader/blob/8864be372a83921f15906ae80752be9d6a300b81/include/class_loader/class_loader.hpp#L117-L132) was missing from the API for the ROS2 version; was this intentional? If not, we will create a PR adding it.

**Comment by dirk-thomas** [comment]
While the methods have different names on the ROS 2 branches they should offer the same functionality:

https://github.com/ros/class_loader/blob/9c0875c8a861b577e8d6e4e848cee3646a14c063/include/class_loader/class_loader.hpp#L124-L125

https://github.com/ros/class_loader/blob/9c0875c8a861b577e8d6e4e848cee3646a14c063/include/class_loader/class_loader.hpp#L146-L147

https://github.com/ros/class_loader/blob/9c0875c8a861b577e8d6e4e848cee3646a14c063/include/class_loader/class_loader.hpp#L169-L170

**Comment by Levi-Armstrong** [comment]
Ah, I missed the fact that `createInstance` returned a shared pointer. Thank you.
