### ISSUE TITLE
Can we have a 0.4.2 tag?

### ISSUE THREAD

**Issue by seanyen** [ros/class_loader#167]
It would be nice to have a `0.4.2` version tag: https://github.com/ros/class_loader/commit/8864be372a83921f15906ae80752be9d6a300b81

Thanks!

**Comment by hidmic** [comment]
Oof, it's been a while. I don't know what happened here. It looks like the `0.4.2` commit was tagged with `0.5.0`? @nuclearsandwich

**Comment by nuclearsandwich** [comment]
> Oof, it's been a while. I don't know what happened here.

> It looks like the `0.4.2` commit was tagged with `0.5.0`?

What gives you that impression? I see the commit 812744d284cd48cf575a15389d106f5d4c8903c0 tagged 0.5.0
and 8864be372a83921f15906ae80752be9d6a300b81 is untagged.

I bumped class_loader in noetic to 0.5.0 to allow patch room in melodic. It seems like I never completed a 0.4.2 release into Melodic.

**Comment by hidmic** [comment]
Uh, yeah, I had a brainfart I think. I'll just push the tag.

**Comment by hidmic** [comment]
Tag added.
