### ISSUE TITLE
rosconsole location being overwritten by class_loader

### ISSUE THREAD

**Issue by davetcoleman** [ros/class_loader#18]
I'm double-posting this issue in hopes that the correct maintainer can address it, thanks! One of them should be closed, of course.
https://github.com/ros/rosconsole_bridge/issues/5

**Comment by mikaelarguedas** [comment]
@davetcoleman is this still an issue on Indigo and newer?

**Comment by davetcoleman** [comment]
I do not recall this issue anymore, so will close since the reposted issue was also closed
