### ISSUE TITLE
undefined reference to `class_loader

### ISSUE THREAD

**Issue by kashifzr** [ros/class_loader#188]
<pre>--- stderr: hardware_interface
/usr/bin/ld: libhardware_interface.so: undefined reference to `class_loader::ClassLoader::isLibraryLoaded()&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `ros::package::getPath(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;)&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `class_loader::systemLibrarySuffix[abi:cxx11]()&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `ros::console::initialize()&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, ros::console::levels::Level)&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `ros::console::print(ros::console::FilterBase*, void*, ros::console::levels::Level, char const*, int, char const*, char const*, ...)&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `boost::filesystem::path::filename() const&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `class_loader::MultiLibraryClassLoader::getAllAvailableClassLoaders()&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `ros::console::setLogLocationLevel(ros::console::LogLocation*, ros::console::levels::Level)&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&amp;, boost::system::error_code*)&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `ros::console::g_initialized&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `class_loader::MultiLibraryClassLoader::getRegisteredLibraries[abi:cxx11]()&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `ros::console::checkLogLocationEnabled(ros::console::LogLocation*)&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `ros::package::getPlugins(std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::vector&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;, std::allocator&lt;std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; &gt; &gt;&amp;, bool)&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&amp;)&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `boost::filesystem::path::parent_path() const&apos;
/usr/bin/ld: libhardware_interface.so: undefined reference to `class_loader::impl::AbstractMetaObjectBase::isOwnedBy(class_loader::ClassLoader const*)&apos;
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_generic_system.dir/build.make:128: test_generic_system] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: CMakeFiles/test_generic_system.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2
---
Failed   &lt;&lt;&lt; hardware_interface [15.7s, exited with code 2]
Aborted  &lt;&lt;&lt; moveit_msgs [26.0s]
Aborted  &lt;&lt;&lt; controller_manager_msgs [37.3s]
Aborted  &lt;&lt;&lt; geometric_shapes [1min 12s]

Summary: 2 packages finished [1min 12s]
  1 package failed: hardware_interface
  3 packages aborted: controller_manager_msgs geometric_shapes moveit_msgs
  3 packages had stderr output: geometric_shapes hardware_interface moveit_msgs
  48 packages not processed
</pre>
How to resolve this issue I am unable to resolve

**Comment by hidmic** [comment]
@kashifzr I think we'll need a bit more information to help you here. Check the [ROS 2 Developer Guide](https://docs.ros.org/en/rolling/Contributing/Developer-Guide.html#issues) for tips on how to file an actionable bug report. Also, http://answers.ros.org/ is a great place to ask questions.

**Comment by kashifzr** [comment]
@hidmic. I am trying to build Moveit2 from Source on Ubuntu 20.04 Focal. Though I can Use Binary Install option to install Moveit2 but I need to used Geometric_Shapes to install another package where Geometric Shapes is being refer. On ubuntu 18.04 building moveit2 from Source works normally but here on Ubuntu 20.04 it makes issues.

**Comment by daohu527** [comment]
seems resolved
https://github.com/ros-planning/moveit2/issues/678

**Comment by clalancette** [comment]
Based on the latest comment, closing this out.  If you are still having problems, feel free to reopen.
