### ISSUE TITLE
Migrate FindPoco.cmake to cmake_modules

### ISSUE THREAD

**Issue by mitchellwills** [ros/class_loader#21]
I was looking to potentially use the Poco library in one of my projects and I noticed that class_loader has it's own private copy of FindPoco. Is there any reason for this or can it be migrated to cmake_modules?

**Comment by mirzashah** [comment]
class_loader was intended originally to be a ROS-agnostic package...but given that it's a ROS catkin package anyway...I'm not sure there's any reason for it anymore. Also at the time, there was no cmake_modules package

**Comment by esteve** [comment]
Sounds good, I'll submit a PR to https://github.com/ros/cmake_modules/ and move `FindPoco.cmake` there.

Thanks!
