### ISSUE TITLE
class_loader generating compilation errors

### ISSUE THREAD

**Issue by toyoxx** [ros/class_loader#44]
Hello.

I'm trying to install ROS Jade on macOS 10.12.1, using clang++ and libc++, but I keep getting the following error when trying to compile ROS (packages as nodelet_math_tutorial or rqt_gui). The compiler says there's no definition of several variables in the global namespace and the stack traces seem to point that the problem is coming from `class_loader`. You can see the output [here](https://gist.github.com/toyoxx/8a8123ecf5a0ee7828a3f5745e125697). I have tried several approaches, such as changing from libc++ to libstdc++, but then its deprecated and some other packages fail. I thought initially it was a problem that I could solve in each of the packages, so I posted in common_tutorials, but then they pointed me in this direction. I hope you can help me with this!! 

Thanks

**Comment by Joschka1** [comment]
same problems her. 
macOS 10.12.1 
Xcode 7.8 & Xcode 8.1

**Comment by spmaniato** [comment]
Btw, this isn't unique to `10.12` I'm getting the same errors on `10.11.6` (Xcode 8.1, ROS Indigo)

**Comment by mikaelarguedas** [comment]
Thanks for reporting the issue. Could you confirm that this error appeared since https://github.com/ros/class_loader/commit/ca6a6127835e06d7b75f353eb053d89f93dccb8f has been merged (leveraging unique_ptr provided by c++11)? or is the problem also present for version 0.3.4 of `class_loader` ?

**Comment by mikaelarguedas** [comment]
Closing this in favor of https://github.com/mikepurvis/ros-install-osx/issues/73#issuecomment-264609106 and https://github.com/ros/rosdistro/issues/13333#issuecomment-269440618 where the answer has been posted
