### ISSUE TITLE
[ros2] poco 1.7.8 on macosx - undefined symbols

### ISSUE THREAD

**Issue by Karsten1987** [ros/class_loader#46]
I am compiling against the ROS2 branch.

```
Undefined symbols for architecture x86_64:
  "Poco::SharedLibrary::suffix()", referenced from:
      class_loader::systemLibrarySuffix() in class_loader.cpp.o
  "Poco::SharedLibrary::unload()", referenced from:
      class_loader::impl::unloadLibrary(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, class_loader::ClassLoader*) in class_loader_core.cpp.o
  "Poco::SharedLibrary::SharedLibrary(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      class_loader::impl::loadLibrary(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, class_loader::ClassLoader*) in class_loader_core.cpp.o
  "Poco::SharedLibrary::isLoaded() const", referenced from:
      class_loader::impl::isLibraryLoadedByAnybody(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in class_loader_core.cpp.o
      class_loader::impl::unloadLibrary(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, class_loader::ClassLoader*) in class_loader_core.cpp.o
  "typeinfo for Poco::RuntimeException", referenced from:
      GCC_except_table47 in class_loader_core.cpp.o
  "typeinfo for Poco::NotFoundException", referenced from:
      GCC_except_table41 in class_loader_core.cpp.o
  "typeinfo for Poco::LibraryLoadException", referenced from:
      GCC_except_table41 in class_loader_core.cpp.o
  "typeinfo for Poco::LibraryAlreadyLoadedException", referenced from:
      GCC_except_table41 in class_loader_core.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libclass_loader.dylib] Error 1
make[1]: *** [CMakeFiles/class_loader.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by TateXu** [comment]
Hi, I met the same problem when I was installing ROS, did you manage to figure it out?

**Comment by Karsten1987** [comment]
are you trying to compile ROS2? If so, the current [ROS2.repos](https://github.com/ros2/ros2/blob/master/ros2.repos) contains a poco-vendor package, which downloads 1.7.7. The way I managed to compile ROS2 is to unlink poco from brew and install the poco-vendor package. 

```
brew unlink poco
ament build 
```

While this solution works, I am hesitating to close this issue, because I believe that's not a long-term solution.

Please report here on that issue whether this workout works for you or not.

**Comment by mikaelarguedas** [comment]
Tested with @Karsten1987 on a ~~High Sierra~~ Sierra machine with recently released poco 1.9.0. It seems to not be an issue anymore. I'll give it a shot on a Sierra machine and close this if it's resolved there as well

**Comment by mikaelarguedas** [comment]
CI on the ros2 branch for macos (using high sierra) passes as of https://github.com/ros/class_loader/pull/106 so I'm going to close this. Feel free to comment if you face ethe issue again and we can reopen

**Comment by t0ny-peng** [comment]
@Karsten1987 Hi. I'm building ROS2 with Clang 6.0/libc++ 6.0 on **Ubuntu** and also had the same error with package `libclass_loader`. My Poco vendor version is 1.9.0. The error message is:
```
libclass_loader.so: undefined reference to `Poco::SharedLibrary::SharedLibrary(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
```

Have you found a long term solution?

**Comment by Karsten1987** [comment]
So the latest master repo definitely compiles correctly with the poco vendor package with clang (osx though).
I haven't tested it on ubuntu with clang and i believe the buildfarm is using gcc on ubuntu. 

Are you running into this problem also when compiling with the [latest repos file](https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos)? also make sure that no ros1 components are sourced at compile time, as they could interfere with it.

I try to give it a shot in a docker container as soon as i have some time.

**Comment by t0ny-peng** [comment]
No worries. I figured it out. I used a toolchain file to set CMAKE_CXX_COMPILER to clang. But it was not pupolated to Poco project. So I’m in a situation where Poco is built with GNU compiler while other packages use Clang.

Setting CC and CXX environment solves the problem. Thanks.

Best,

--------
Hao Peng
Email: hao@pengs.us

**Comment by kongdaqing** [comment]
> are you trying to compile ROS2? If so, the current [ROS2.repos](https://github.com/ros2/ros2/blob/master/ros2.repos) contains a poco-vendor package, which downloads 1.7.7. The way I managed to compile ROS2 is to unlink poco from brew and install the poco-vendor package.
> 
> ```
> brew unlink poco
> ament build 
> ```
> 
> While this solution works, I am hesitating to close this issue, because I believe that's not a long-term solution.
> 
> Please report here on that issue whether this workout works for you or not.

thanks!
