### ISSUE TITLE
Package not configuring

### ISSUE THREAD

**Issue by hemker** [ros/class_loader#89]
Hey, 
although declared as stand alone, the CMakeLists.txt contains an install target called PROGRAMS, the cmake configure phase thus can't complete (because the target PROGRAMS is not declared in non-ros installations). We're using the class_loader in ROCK.

**Comment by mikaelarguedas** [comment]
Thanks @hemker for reporting. This looks similar to https://github.com/ros/class_loader/pull/88

Can you confirm that it would solve your issue ?

**Comment by hemker** [comment]
@mikaelarguedas 
Perfect, the PR solves the configure issue.
Thank you.

**Comment by mikaelarguedas** [comment]
Fixed in #88
