### ISSUE TITLE
std::shared_ptr ?

### ISSUE THREAD

**Issue by bmagyar** [ros/class_loader#92]
We have mostly removed `boost::shared_ptr` in favour of `std::shared_ptr`. Is [`createInstance()`](https://github.com/ros/class_loader/blob/melodic-devel/include/class_loader/class_loader.hpp#L120) not the preferred way to load plugins?

**Comment by mikaelarguedas** [comment]
Yes, the `ros2` branch of this repo doesn't have any dependency on boost anymore. I was hoping to provide an std version of the various APIs by melodic but didnt get around doing it yet.

As modifying the signature of `createInstance` will require any downstream package to adapt their code, I was thinking of creating a `createSharedInstance` equivalent and deprecating the existing one.
Would that work for your use case ? (this will likely need pluginlib to do the same to be really useful, there's work in that direction [here](https://github.com/ros/pluginlib/pull/67/files#diff-ca2b6071ef290a8731c40a238f8e40a8R110) as well, but same thing not sure It'll be released in time for melodic)

**Comment by bmagyar** [comment]
Although the header file deprecation has been merged into Kinetic already,
I think many packages have already branched out. I'd opt for getting the
whole package done for Melodic :)

**Comment by mikaelarguedas** [comment]
>  the header file deprecation has been merged into Kinetic already,

The new headers are available on all active ROS distros (including indigo) so there should be no requirement for maintainers to branch out. And the headers should not be deprecated for Kinetic (or any distro except melodic) otherwise I messed up something along the way o_O.

> I'd opt for getting the whole package done for Melodic :)

Agreed, that's the desired outcome, and I'll try to make it happen, in any spare cycle I can find.

Can you confirm that the API suggested above satisfies your use case?

**Comment by bmagyar** [comment]
The header deprecation is all ok but I suppose many decided not to live with those warnings :) 

Thanks, it would be great to have this for Melodic!

Most `XyzSharedPtr` already use `std::shared_ptr`, now packages either have a consistent pointer typedef set and they explicitly declare `pluginlib`-returned instances to use `boost::shared_ptr` or they have a mix of the two in the pointer typedefs.

The suggested API would provide a solution that can work for the long run.
